Class {
	#name : 'ConwayModelManifest',
	#superclass : 'CMModelManifest',
	#category : 'Cormas-ExampleModels',
	#package : 'Cormas-ExampleModels'
}

{ #category : 'baselines' }
ConwayModelManifest class >> baselineName [

	^ 'ConwayModel'
]

{ #category : 'parameters' }
ConwayModelManifest class >> githubRepositoryName [

	^ 'conway-model'
]

{ #category : 'as yet unclassified' }
ConwayModelManifest class >> modelName [
	
	^ 'Conway'
]
