Class {
	#name : 'DemoAggregatesModelManifest',
	#superclass : 'CMModelManifest',
	#category : 'Cormas-ExampleModels',
	#package : 'Cormas-ExampleModels'
}

{ #category : 'parameters' }
DemoAggregatesModelManifest class >> baselineName [

	^'DemoAggregates'
]

{ #category : 'parameters' }
DemoAggregatesModelManifest class >> githubRepositoryName [

	^ 'demo-aggregates'
]

{ #category : 'parameters' }
DemoAggregatesModelManifest class >> modelName [

	^ 'Demo aggregates'
]
