Class {
	#name : 'ShellingModelManifest',
	#superclass : 'CMModelManifest',
	#category : 'Cormas-ExampleModels',
	#package : 'Cormas-ExampleModels'
}

{ #category : 'baselines' }
ShellingModelManifest class >> baselineName [

	^ 'ShellingModel'
]

{ #category : 'parameters' }
ShellingModelManifest class >> githubRepositoryName [

	^ 'shelling-model'
]

{ #category : 'as yet unclassified' }
ShellingModelManifest class >> modelName [
	
	^ 'Shelling'
]
